# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewPwdgen < Formula
  desc "Generate secure passwords using your terminal"
  homepage "https://github.com/PauSabatesC/pwdgen"
  version "0.1.3"
  license "MPL-2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.3/pwdgen_0.1.3_Darwin_arm64.tar.gz"
      sha256 "1b8bf6724a6fe15e6275c314de4214f273118cccfeacb534e6a07971bae0df5f"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.3/pwdgen_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "ef4c8e3af5f6ef955315d403e47f8c3682e9cc92029cb802005442859d73e6f7"

      def install
        bin.install "pwdgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.3/pwdgen_0.1.3_Linux_armv6.tar.gz"
      sha256 "b2d43d91f2dcafbd97401e0ea0145349ec2ebb668a338f2db93b9b3fcaf6630a"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.3/pwdgen_0.1.3_Linux_x86_64.tar.gz"
      sha256 "3005d0be102a2f01433eb4c21f40de2e105183d28236721bfed0fee420602980"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.3/pwdgen_0.1.3_Linux_arm64.tar.gz"
      sha256 "03a1faa6f9410aa43dcef892992731909f78830b133cd8bd1919dc49aa95b749"

      def install
        bin.install "pwdgen"
      end
    end
  end
end
