# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwdgen < Formula
  desc "Generate secure passwords using your terminal"
  homepage "https://github.com/PauSabatesC/pwdgen"
  version "0.1.4"
  license "MPL-2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.4/pwdgen_0.1.4_Darwin_arm64.tar.gz"
      sha256 "c277cce32f1887c3550b591c7e76571e0cfe47aeec6a85f8b3ccb056ee6713b5"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.4/pwdgen_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "d62cfd566000b5db29ae6efbedcf5aff0f890ab552eb2ae81d0418781caa4ad4"

      def install
        bin.install "pwdgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.4/pwdgen_0.1.4_Linux_armv6.tar.gz"
      sha256 "c1fcedaa3f4506e3df5a5c8101ab07e55406664fde572c837c88fbcf13e17a00"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.4/pwdgen_0.1.4_Linux_x86_64.tar.gz"
      sha256 "3fa3b6783f9ae3812948c428cab78e13b0f22125a2ac66dc732c74c324e3355d"

      def install
        bin.install "pwdgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/pwdgen/releases/download/v0.1.4/pwdgen_0.1.4_Linux_arm64.tar.gz"
      sha256 "0347e463756f51e21fb8d7bc0acb42e43ab5539ce75b851c0e3308ecc6ae0184"

      def install
        bin.install "pwdgen"
      end
    end
  end
end
