name: dev-build

on:
  push:
    branches:
      - '*'
      - '!master'

permissions:
  contents: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: version=${{ steps.tagName.outputs.tag }}
          push: true
          tags: pausc/pwdgen:dev

